// Guide content for the VPS ChatGPT wizard (index.html). Facts come from docs/vps-and-n8n.md,
// docs/getting-started.md, docs/troubleshooting.md and docs/n8n-configuration.md.
// Within a chapter the engine shows the first visible tip whose done condition is unmet, so
// tips inside closed disclosures come first and only appear once the person opens them.

const wait = (id) => ({
  id,
  target: "#operation-progress",
  action: "wait",
  title: "Wait for this step",
  say: "Relmio is working on your server. Keep this page open until the bar finishes.",
  done: "hidden:#operation-progress",
});

export const GUIDE = {
  page: "vps",
  title: "Connect n8n on your VPS to your ChatGPT plan",
  intro: "This guide points at each box and button in order and tells you what to type. You can hide it or skip it at any time.",
  chapters: [
    {
      id: "route",
      label: "Choose your setup",
      panel: "#setup-choices",
      badge: "Route chosen",
      tips: [
        {
          id: "chatgpt-route",
          target: "#openai-vps-route",
          action: "press",
          title: "Pick ChatGPT sign-in",
          say: "This card connects n8n on your VPS to your ChatGPT plan. A VPS is a computer you rent that stays on all day in a data center. Press the card to start.",
          done: "clicked",
        },
        {
          id: "other-routes",
          target: "#vps-supergrok-start",
          action: "read",
          title: "Other ways to connect",
          say: "Want Grok, a private model with no sign-in, or a setup on this computer? Pick one of the other cards. Each one opens its own guided page.",
          done: "manual",
        },
        {
          id: "hosting",
          target: "#hosting-options-link",
          action: "read",
          title: "Not sure where to host",
          say: "Compare hosting routes shows which providers Relmio can set up for you and which need files you apply yourself.",
          done: "manual",
        },
      ],
    },
    {
      id: "signin",
      label: "Sign in to ChatGPT",
      panel: "#chatgpt-setup",
      badge: "Plan connected",
      tips: [
        {
          id: "open-link",
          target: "#login-link",
          action: "press",
          title: "Open the sign-in page",
          say: "If no ChatGPT page opened, press this to open the sign-in in a new tab.",
          done: "clicked",
        },
        {
          id: "finish-browser",
          target: "#stop-login-button",
          action: "wait",
          title: "Finish in the ChatGPT tab",
          say: "Relmio is waiting for you to sign in on the ChatGPT page. Come back here when it says you are done. Press Stop ChatGPT sign-in only to cancel.",
          done: "hidden:#stop-login-button",
        },
        {
          id: "finish-pending",
          target: "[data-siwc=finish]",
          action: "press",
          title: "Finish an open sign-in",
          say: "A sign-in was started but never finished. Pick it in the Unfinished sign-in list, then press Finish sign-in.",
          done: "clicked",
        },
        {
          id: "accept-notice",
          target: "[data-siwc=welcome-accept]",
          action: "press",
          title: "Read the plan notice",
          say: "Your ChatGPT plan pays for these requests, and OpenAI's limits apply. Press Continue when you have read it.",
          done: "clicked",
        },
        {
          id: "open-notice",
          target: "[data-siwc=welcome-open]",
          action: "press",
          title: "Open the plan notice",
          say: "Plan use is allowed. Press Review plan notice and read it before you go on.",
          done: "clicked",
        },
        {
          id: "grant",
          target: "[data-siwc=grant]",
          action: "press",
          title: "Allow ChatGPT plan use",
          say: "You are signed in, but plan use is not allowed yet. Press Allow ChatGPT plan use and approve it on the ChatGPT page. Signing in and allowing plan use are separate steps.",
          done: "clicked",
        },
        {
          id: "resume",
          target: "[data-siwc=resume]",
          action: "press",
          title: "Turn plan use back on",
          say: "Plan use is paused for this account. Press Use ChatGPT plan to turn it back on.",
          done: "clicked",
        },
        {
          id: "sign-in-again",
          target: "[data-siwc=return]",
          action: "press",
          title: "Sign in again",
          say: "If the status says this account needs a fresh sign-in, press Sign in again. Relmio never reuses an old sign-in.",
          done: "visible:[data-siwc=plan-badge]",
        },
        {
          id: "continue",
          target: "[data-siwc=new]",
          action: "press",
          title: "Continue with ChatGPT",
          say: "Press Continue with ChatGPT and sign in on the page that opens. Signed in before? Pick that account in the ChatGPT account list instead.",
          find: "Use the ChatGPT account whose plan you want n8n to use. Relmio never imports your personal Codex login.",
          done: "visible:[data-siwc=plan-badge]",
        },
        {
          id: "next",
          target: "#signin-next",
          action: "press",
          title: "Go to the server check",
          say: "The status says the plan is ready. Press Check the server.",
          done: "clicked",
        },
        {
          id: "usage",
          target: "[data-siwc=usage]",
          action: "read",
          title: "Watch your plan limits",
          say: "Manage usage opens ChatGPT's usage page. Check your plan's limits there at any time.",
          done: "manual",
        },
        {
          id: "recover",
          target: "[data-siwc=recover]",
          action: "read",
          title: "Already installed before",
          say: "Use Recover or manage an installation to reach the controls for a sidecar you set up earlier. Relmio checks the server first.",
          done: "manual",
        },
      ],
    },
    {
      id: "server",
      label: "Check your server",
      panel: "#vps-form",
      badge: "Server checked",
      tips: [
        wait("server-wait"),
        {
          id: "host",
          target: "#host",
          action: "type",
          title: "Type your server address",
          say: "Type the IP address or name of your VPS. Type the address only, with nothing like ssh root@ in front.",
          example: "203.0.113.10",
          find: "Your VPS provider shows the server's IP address or hostname with your server's details.",
          done: "filled",
        },
        {
          id: "port",
          target: "#port",
          action: "type",
          title: "Check the SSH port",
          say: "SSH is the secure way Relmio logs in to your server to run commands. Keep 22 unless your server uses another SSH port.",
          example: "22",
          done: "filled",
        },
        {
          id: "check",
          target: "#fingerprint-button",
          action: "press",
          title: "Check the server identity",
          say: "Press Check this server. Relmio reads the server's fingerprint before it sends any password.",
          done: "visible:#fingerprint-box",
        },
        {
          id: "fingerprint",
          target: "#fingerprint-confirm",
          action: "check",
          title: "Compare the fingerprint",
          say: "A fingerprint is your server's ID card, a long code that only this server has. Compare it with a copy you trust, then tick the box. If it does not match, stop here.",
          find: "Get the fingerprint from your VPS provider or administrator through a channel you trust, such as the provider's console. It is the server's host key, not your own login key.",
          done: "checked",
        },
        {
          id: "username",
          target: "#username",
          action: "type",
          title: "Your SSH username",
          say: "This route needs root, the server's main administrator account.",
          example: "root",
          find: "Use the real SSH username for your server's image.",
          done: "filled",
        },
        {
          id: "password",
          target: "#password",
          action: "type",
          title: "Type the server password",
          say: "Type the SSH password for this server. Relmio uses it to connect and clears it afterwards. To use an SSH key, choose Local SSH agent in SSH authentication.",
          find: "For a key, load it into your SSH agent with ssh-add before you start Relmio. Relmio never asks for the key file.",
          done: "filled",
        },
        {
          id: "connect",
          target: "#connect-button",
          action: "press",
          title: "Connect",
          say: "Press Connect. Relmio logs in and looks at Docker and n8n without changing anything.",
          done: "clicked",
        },
      ],
    },
    {
      id: "n8n",
      label: "Choose your n8n",
      panel: "#container-select",
      badge: "n8n found",
      tips: [
        {
          id: "owner-check",
          target: "#vps-owner-check",
          action: "press",
          title: "Check the installed account",
          say: "Press Check installed account. Relmio reads which ChatGPT account the sidecar uses and whether a newer sidecar is ready. A sidecar is the small helper Relmio runs next to n8n.",
          done: "clicked",
        },
        {
          id: "owner-inspect-confirm",
          target: "#vps-owner-inspect-confirm",
          action: "check",
          title: "Allow a one-time look",
          say: "The sidecar is stopped, so Relmio needs a short read to see its owner. It adds a temporary Docker helper and never touches n8n. Tick the box to allow it.",
          done: "checked",
        },
        {
          id: "owner-inspect",
          target: "#vps-owner-inspect",
          action: "press",
          title: "Inspect the stopped sidecar",
          say: "Press Inspect stopped owner to read the account.",
          done: "clicked",
        },
        {
          id: "update-review",
          target: "#vps-owner-update-review",
          action: "press",
          title: "Review the sidecar update",
          say: "Press Review sidecar update to see whether the sidecar needs rebuilding. Your ChatGPT sign-in and your Relmio key stay the same.",
          done: "clicked",
        },
        {
          id: "update-confirm",
          target: "#vps-owner-update-confirm",
          action: "check",
          title: "Approve the rebuild",
          say: "Tick the box to let Relmio rebuild and restart only its own sidecar. n8n keeps running. The check and the review each expire after five minutes.",
          done: "checked",
        },
        {
          id: "update-apply",
          target: "#vps-owner-update-apply",
          action: "press",
          title: "Update the sidecar",
          say: "Press Update the sidecar. The old one keeps serving while the new image builds.",
          done: "clicked",
        },
        {
          id: "usage-refresh",
          target: "#vps-usage-refresh",
          action: "press",
          title: "See your plan and usage",
          say: "Press Refresh usage to read the requests Relmio sent for this account in the last 30 days. It only reads from your server. If the account check has expired, press Check installed account first.",
          done: "clicked",
        },
        {
          id: "usage-read",
          target: "#vps-usage-view",
          action: "read",
          title: "Read your request counts",
          say: "These are the requests and tokens that went through Relmio, not your plan's limits. Manage usage opens ChatGPT, which shows your limits and reset times.",
          done: "manual",
        },
        {
          id: "models-confirm",
          target: "#vps-owner-models-confirm",
          action: "check",
          title: "Model checks, optional",
          say: "Model checks send a short test, Reply with OK, so n8n lists only models that answer. Each test uses a little of your plan. Tick the box if you want them.",
          done: "checked",
        },
        {
          id: "models-on",
          target: "#vps-owner-models-on",
          action: "press",
          title: "Turn on model checks",
          say: "Press Turn on model checks. Testing up to 12 models can take a few minutes.",
          done: "clicked",
        },
        {
          id: "models-off-confirm",
          target: "#vps-owner-models-off-confirm",
          action: "check",
          title: "Turn model checks off",
          say: "Tick this and press Turn off model checks if you no longer want test requests. New models then show in n8n without a test.",
          done: "checked",
        },
        {
          id: "models-list",
          target: "#vps-owner-models-status",
          action: "read",
          title: "Read your model list",
          say: "In n8n means n8n can see the model now. Ready means it answered a test or a real request. Use Copy ID to copy a model name for n8n.",
          done: "manual",
        },
        {
          id: "images-confirm",
          target: "#vps-owner-images-confirm",
          action: "check",
          title: "Image add-on, optional",
          say: "Images use a separate Codex sign-in, and OpenAI does not document this route for other apps. It can stop working at any time. Tick the box only if you want images.",
          done: "checked",
        },
        {
          id: "images-start",
          target: "#vps-owner-images-start",
          action: "press",
          title: "Sign in for images",
          say: "Press Sign in for images. Relmio then shows a code.",
          done: "clicked",
        },
        {
          id: "images-code",
          target: "#vps-owner-images-link",
          action: "press",
          title: "Enter the code at OpenAI",
          say: "Open the Codex sign-in page, sign in with the same ChatGPT account and type the code shown. Only enter it at auth.openai.com. The code expires after 15 minutes.",
          done: "hidden:#vps-owner-images-pending",
        },
        {
          id: "images-signout",
          target: "#vps-owner-images-signout-confirm",
          action: "check",
          title: "Turn images off",
          say: "To stop images, tick this and press Sign out of images. Relmio deletes the Codex sign-in from the server and asks OpenAI to revoke it.",
          done: "checked",
        },
        {
          id: "owner-confirm",
          target: "#vps-owner-confirm",
          action: "check",
          title: "Pause or sign out",
          say: "Pause, resume and sign-out stop only this sidecar for a moment. Tick the box first, then press the action you want.",
          done: "checked",
        },
        {
          id: "owner-background",
          target: "#vps-owner-background-confirm",
          action: "check",
          title: "Allow background use again",
          say: "Turning plan use back on needs your approval for n8n background workflows again. Tick the box, then press Use ChatGPT plan.",
          done: "checked",
        },
        wait("n8n-wait"),
        {
          id: "container",
          target: "#container-select",
          action: "choose",
          title: "Pick your n8n",
          say: "This list shows the n8n containers running on your server. A container is a sealed box that runs one app, like n8n. Pick the one you use.",
          find: "Only running n8n is listed. If yours is missing, start it the way you normally do, then choose Retry discovery.",
          done: "manual",
        },
        {
          id: "network",
          target: "#network-select",
          action: "choose",
          title: "Pick the private network",
          say: "A Docker network is a private hallway that lets containers talk to each other. The sidecar joins this one so n8n can reach it. n8n itself does not change.",
          find: "Pick a network your n8n is already on. Never publish port 10531 to work around a missing network.",
          done: "manual",
        },
        {
          id: "searxng",
          target: "#manage-vps-searxng",
          action: "check",
          title: "Web search, optional",
          say: "Tick this only if n8n's Assistant needs private web search. It is off by default and stays on the private network.",
          done: "manual",
        },
        {
          id: "review",
          target: "#review-button",
          action: "press",
          title: "Review the plan",
          say: "Press Review. Nothing is written to your server yet.",
          done: "clicked",
        },
        {
          id: "manage",
          target: "#manage-vps-integration",
          action: "read",
          title: "Manage an existing install",
          say: "Set up Relmio here before? Pick the companion above and press this button to manage it. For a first install, press Review instead.",
          done: "manual",
        },
        {
          id: "owner-open",
          target: "#vps-siwc-owner",
          action: "read",
          title: "Check what is installed",
          say: "Open Manage the installed ChatGPT session to check the account, update the sidecar, see models or add images.",
          done: "manual",
        },
        {
          id: "recovery",
          target: "#vps-siwc-recovery",
          action: "read",
          title: "Fix an interrupted install",
          say: "If an earlier install stopped partway, open Recover a transfer or staged installation here. Relmio reviews first and asks again before it writes.",
          done: "manual",
        },
      ],
    },
    {
      id: "review",
      label: "Review the plan",
      panel: "#review-will-list",
      badge: "Plan approved",
      tips: [
        wait("review-wait"),
        {
          id: "plan",
          target: "#ssh-review-identity",
          action: "read",
          title: "Check every line",
          say: "Make sure this is your server, your ChatGPT account and your n8n. The lists below show what Relmio will do and what it never does.",
          done: "manual",
        },
        {
          id: "confirm",
          target: "#install-confirm",
          action: "check",
          title: "Approve the write",
          say: "Tick this to let Relmio write only its own folder, /docker/n8n-openai-oauth. Back up your n8n workflows before you approve.",
          done: "checked",
        },
        {
          id: "background",
          target: "#background-consent",
          action: "check",
          title: "Allow background workflows",
          say: "n8n runs workflows on its own, even when you are away. Tick this to let those workflows use this account's ChatGPT plan.",
          done: "checked",
        },
        {
          id: "migration",
          target: "#vps-migration-consent",
          action: "check",
          title: "Replace the old sidecar",
          say: "An older Relmio sidecar is on this server. Tick this to stop only that one and keep its old sign-in offline. You will paste a new key into n8n.",
          done: "checked",
        },
        {
          id: "replacement",
          target: "#vps-replacement-consent",
          action: "check",
          title: "Use a fresh account",
          say: "The installed sidecar is signed out. Tick this to replace it with the account you just signed in.",
          done: "checked",
        },
        {
          id: "install",
          target: "#install-button",
          action: "press",
          title: "Install",
          say: "Press Install. Building the sidecar can take several minutes, so keep this page open.",
          done: "clicked",
        },
      ],
    },
    {
      id: "ready",
      label: "Connect n8n",
      panel: "#done-title",
      badge: "n8n connected",
      tips: [
        {
          id: "model",
          target: "#result-model-picker",
          action: "choose",
          title: "Pick a model",
          say: "Choose a model from your account's list and copy its ID into the OpenAI Chat Model node. A listed model can still fail for a request.",
          done: "changed",
        },
        {
          id: "http-recipe",
          target: "#copy-http-recipe",
          action: "press",
          title: "HTTP Request node recipe",
          say: "Using an HTTP Request node instead? Press Copy recipe and fill in the node with these values.",
          done: "clicked",
        },
        {
          id: "sandbox-key",
          target: "[data-copy-target=assistant-result-sandbox-key]",
          action: "press",
          title: "Copy the sandbox key",
          say: "Relmio shows this sandbox key only once. Copy it now and keep it safe.",
          done: "clicked",
        },
        {
          id: "assistant-settings",
          target: "#assistant-result-settings",
          action: "read",
          title: "Add these to n8n yourself",
          say: "Copy these lines into n8n's settings the way you normally deploy n8n. Relmio never edits or restarts n8n.",
          done: "manual",
        },
        {
          id: "usage-limit",
          target: "#result-readiness-usage",
          action: "press",
          title: "Usage limit reached",
          say: "The account reached its plan usage limit. Press Manage usage to check it in ChatGPT.",
          done: "clicked",
        },
        {
          id: "key",
          target: "[data-copy-target=result-key]",
          action: "press",
          title: "Copy your Relmio key",
          say: "An API key is a password one app uses to talk to another. This one lets n8n talk to the sidecar and is shown only once, so copy it now. It is not an OpenAI API key.",
          done: "clicked",
        },
        {
          id: "credential",
          target: "#copy-settings",
          action: "press",
          title: "Fill in the n8n credential",
          say: "In n8n, create an OpenAI credential. Paste the Base URL and use the Relmio key as the API key. Leave Organization ID empty.",
          example: "http://n8n-openai-oauth:10531/v1",
          done: "clicked",
        },
        {
          id: "responses",
          target: "#responses-api-notice",
          action: "read",
          title: "Turn Use Responses API on",
          say: "In the OpenAI Chat Model node, version 1.3, turn Use Responses API on. Then pick a model from the list.",
          done: "manual",
        },
        {
          id: "test",
          target: "#result-readiness",
          action: "read",
          title: "Run a first test",
          say: "In n8n, send a short prompt and check for a real answer. A model in the list is not proof that a request will finish.",
          example: "Reply with exactly: bridge works",
          done: "manual",
        },
        {
          id: "usage-summary",
          target: "#result-usage",
          action: "read",
          title: "Where to see your usage",
          say: "Relmio counts each request n8n sends through the sidecar. To see the counts later, open Manage the installed ChatGPT session in Choose your n8n and press Refresh usage.",
          done: "manual",
        },
        {
          id: "another",
          target: "#setup-another-vps",
          action: "press",
          title: "Set up something else",
          say: "Press Set up another option to add Grok, a local model or another route. The sidecar keeps running when you close this wizard.",
          done: "manual",
        },
      ],
    },
  ],
  finish: {
    title: "Setup complete",
    say: "n8n on your server can now use your ChatGPT plan through the private sidecar. You can close this wizard with Control+C, and the sidecar keeps running.",
    next: [
      "Paste the Base URL and Relmio key into an n8n OpenAI credential",
      "Turn Use Responses API on in the OpenAI Chat Model node",
      "Run a short test workflow",
      "Open Manage usage in ChatGPT to watch your plan limits",
    ],
  },
};
