// Guide content for the hosting planner (hosting.html). Facts come from the page copy and
// docs/hosting-compatibility.md. Making a plan reads no server and writes nothing remote.

export const GUIDE = {
  page: "hosting",
  title: "Compare hosting options",
  intro: "This guide helps you pick where to run Relmio's companions and, when needed, download a plan you apply yourself. Nothing here touches a server.",
  chapters: [
    {
      id: "choose",
      label: "Compare hosting",
      panel: "#hosting-choose",
      badge: "Host compared",
      tips: [
        {
          id: "provider",
          target: "#hosting-provider",
          action: "choose",
          title: "Check your hosting provider",
          say: "Hostinger KVM VPS is selected because Relmio is tested on it and on local Docker. If you use another company, pick it here; other providers are experimental.",
          done: "manual",
        },
        {
          id: "component",
          target: "#hosting-component",
          action: "choose",
          title: "Pick what to set up",
          say: "Pick the part you want, such as Local model or OpenAI bridge. The line below then says whether Relmio can set it up there.",
          done: "changed",
        },
        {
          id: "capability",
          target: "#hosting-capability",
          action: "read",
          title: "Read what is possible",
          say: "Managed means Relmio sets it up with checks and a final confirmation. Manual means you get files to apply yourself. External means it needs another service.",
          done: "manual",
        },
        {
          id: "managed",
          target: "#hosting-managed-link",
          action: "press",
          title: "Open the managed setup",
          say: "Relmio can set this up for you. Press Open managed setup to start the guided wizard.",
          done: "clicked",
        },
        {
          id: "continue",
          target: "#hosting-continue",
          action: "press",
          title: "Continue to the details",
          say: "Press Continue to add the details for a manual plan.",
          done: "clicked",
        },
        {
          id: "notes",
          target: ".hosting-notes-trigger",
          action: "read",
          title: "Login notes and sources",
          say: "Login notes and sources shows how this provider signs you in and where the facts come from.",
          done: "manual",
        },
        {
          id: "matrix",
          target: "#hosting-matrix",
          action: "read",
          title: "Read the table",
          say: "Each row is a kind of hosting and each column is a part Relmio can add. The legend under the table explains the marks.",
          done: "manual",
        },
      ],
    },
    {
      id: "details",
      label: "Add plan details",
      panel: "#hosting-details",
      badge: "Details added",
      tips: [
        {
          id: "model",
          target: "#hosting-model",
          action: "choose",
          title: "Pick a model",
          say: "Pick one of the approved models. You still check downloads, storage and memory on the host yourself.",
          done: "changed",
        },
        {
          id: "inputs",
          target: "#hosting-inputs",
          action: "type",
          title: "Fill in each box",
          say: "Fill in each box for your plan. Never type passwords, API keys, tokens or private keys here.",
          done: "manual",
        },
        {
          id: "generate",
          target: "#hosting-generate",
          action: "press",
          title: "Review the plan",
          say: "Press Review the plan to build the files. Nothing is sent to a server.",
          done: "clicked",
        },
      ],
    },
    {
      id: "review",
      label: "Download your plan",
      panel: "#hosting-review",
      badge: "Plan downloaded",
      tips: [
        {
          id: "facts",
          target: "#hosting-review-facts",
          action: "read",
          title: "Check the plan",
          say: "Relmio does not apply these files. Read the requirements and limits before you use them in your provider account. Never apply them to your existing n8n setup.",
          done: "manual",
        },
        {
          id: "steps",
          target: "#hosting-review-details",
          action: "read",
          title: "Read the steps",
          say: "Open Read plan instructions and file previews for the ordered steps, requirements and limits.",
          done: "manual",
        },
        {
          id: "download",
          target: "#hosting-download-bundle",
          action: "press",
          title: "Download the ZIP",
          say: "Press Download files to get the whole plan. The ZIP keeps the folders and hidden setting files in place.",
          done: "clicked",
        },
      ],
    },
  ],
  finish: {
    title: "Plan ready",
    say: "You have a plan for your hosting provider. Relmio did not change any server.",
    next: [
      "Follow the ordered steps in the plan",
      "Check provider access, private routing, resources and storage",
      "Use a managed setup when your host supports one",
    ],
  },
};
