// Guide content for the local wizard (local.html). Facts come from docs/local-dashboard.md,
// docs/local-endpoints.md, docs/local-n8n-stack.md, docs/local-models.md and
// docs/troubleshooting.md. One configure chapter covers every target: the engine skips tips
// whose target is hidden, so only the fields of the chosen connection are pointed at.

const siwcTips = [
  {
    id: "stop-sign-in",
    target: "#n8n-oauth-link",
    action: "wait",
    title: "Finish in the ChatGPT tab",
    say: "Relmio is waiting for you to sign in on the ChatGPT page. Come back here when it says you are done. Press Stop ChatGPT sign-in only to cancel.",
    done: "hidden:#n8n-oauth-link",
  },
  {
    id: "finish-pending",
    target: "[data-siwc=finish]",
    action: "press",
    title: "Finish an open sign-in",
    say: "A sign-in was started but never finished. Pick it in the Unfinished sign-in list, then press Finish sign-in.",
    done: "clicked",
  },
  {
    id: "accept-notice",
    target: "[data-siwc=welcome-accept]",
    action: "press",
    title: "Read the plan notice",
    say: "Requests count toward the usage in your ChatGPT plan, and OpenAI's limits apply. If you allowed apps to use credits in ChatGPT, credits can be used after the plan limit. Press Continue when you have read it.",
    done: "clicked",
  },
  {
    id: "open-notice",
    target: "[data-siwc=welcome-open]",
    action: "press",
    title: "Open the plan notice",
    say: "Plan use is allowed. Press Review plan notice and read it before you go on.",
    done: "clicked",
  },
  {
    id: "grant",
    target: "[data-siwc=grant]",
    action: "press",
    title: "Allow ChatGPT plan use",
    say: "You are signed in, but plan use is not allowed yet. Press Allow ChatGPT plan use and approve it on the ChatGPT page. Signing in and allowing plan use are separate steps.",
    done: "clicked",
  },
  {
    id: "resume",
    target: "[data-siwc=resume]",
    action: "press",
    title: "Turn plan use back on",
    say: "Plan use is paused for this account. Press Use ChatGPT plan to turn it back on.",
    done: "clicked",
  },
  {
    id: "sign-in-again",
    target: "[data-siwc=return]",
    action: "press",
    title: "Sign in again",
    say: "If the status says this account needs a fresh sign-in, press Sign in again. Relmio keeps the same saved account and replaces its old sign-in.",
    done: "visible:[data-siwc=plan-badge]",
  },
  {
    id: "siwc-continue",
    target: "[data-siwc=new]",
    action: "press",
    title: "Continue with ChatGPT",
    say: "Press Continue with ChatGPT and sign in on the page that opens. Signed in before? Pick that account in the ChatGPT account list instead.",
    find: "Use the ChatGPT account whose plan you want to use. Relmio never imports your personal Codex login.",
    done: "visible:[data-siwc=plan-badge]",
  },
];

export const GUIDE = {
  page: "local",
  title: "Set up a connection on this computer",
  intro: "This guide walks you from the dashboard to a working connection, one box and one button at a time. You can hide it or skip it at any time.",
  chapters: [
    {
      id: "dashboard",
      label: "See what is installed",
      panel: "#local-dashboard",
      badge: "Dashboard checked",
      tips: [
        {
          id: "docker",
          target: "#dashboard-environment",
          action: "read",
          title: "Check that Docker is running",
          say: "Relmio first checks Docker on this computer. Docker is the program that runs apps in sealed boxes called containers. If Docker is not running, start it and press Refresh status.",
          find: "Start Docker Desktop or Docker Engine. It is ready when docker info works in a terminal.",
          done: "manual",
        },
        {
          id: "empty",
          target: "#dashboard-empty-setup",
          action: "press",
          title: "Set up your first connection",
          say: "Nothing is installed yet. Press Choose a connection to start.",
          done: "clicked",
        },
        {
          id: "services",
          target: "#dashboard-services",
          action: "choose",
          title: "Pick a service",
          say: "Each row is one connection Relmio can manage. Choose a row to see its details and the actions it allows.",
          done: "manual",
        },
        {
          id: "actions",
          target: "#dashboard-service-actions",
          action: "read",
          title: "Only checked actions show",
          say: "Relmio shows an action only after it has checked that service. If the state says Stale, press Refresh status first.",
          done: "manual",
        },
        {
          id: "usage-read",
          target: "#dashboard-usage-view",
          action: "read",
          title: "Read your plan and usage",
          say: "These are the requests and tokens n8n sent through Relmio in the last 30 days, not your plan's limits. Manage usage opens ChatGPT, which shows your limits and reset times. Refresh usage reads the counts again.",
          done: "manual",
        },
        {
          id: "new",
          target: "#dashboard-new-setup",
          action: "press",
          title: "Add a connection",
          say: "Press Add connection to set up something new. The steps are Choose, Review, Install and Ready.",
          done: "clicked",
        },
        {
          id: "refresh",
          target: "#dashboard-refresh",
          action: "read",
          title: "Refresh any time",
          say: "Refresh status checks everything again. It only reads and never starts, stops or changes a container.",
          done: "manual",
        },
        {
          id: "usage-nav",
          target: "#dashboard-usage-link",
          action: "press",
          title: "See plan and usage",
          say: "Open Plan and usage to see the ChatGPT account on this computer and the requests n8n sent through Relmio.",
          done: "clicked",
        },
        {
          id: "hosting",
          target: "#dashboard-hosting-link",
          action: "read",
          title: "Rather use a server",
          say: "Compare hosting options shows the routes for a VPS and other hosts.",
          done: "manual",
        },
      ],
    },
    {
      id: "choose",
      label: "Choose a connection",
      panel: "#choose-stage",
      badge: "Connection chosen",
      tips: [
        {
          id: "vps-links",
          target: "#local-route-vps-openai",
          action: "read",
          title: "Server setup instead",
          say: "These links open the guided setup for a VPS. A VPS is a computer you rent that stays on all day in a data center.",
          done: "manual",
        },
        {
          id: "cards",
          target: ".main-connection-choices",
          action: "choose",
          title: "Pick what to set up",
          say: "Each card is one kind of connection. ChatGPT, Grok and local model cards add a helper beside an n8n you already run. Set up new n8n creates a fresh n8n with a public link.",
          find: "Open Connection details and limits below for what each card does.",
          done: "changed",
        },
        {
          id: "choose-continue",
          target: "#choose-continue",
          action: "press",
          title: "Continue",
          say: "Press Continue to fill in the details for your choice.",
          done: "clicked",
        },
        {
          id: "more",
          target: "#more-connections-and-tools",
          action: "read",
          title: "More choices",
          say: "Codex App Server, Codex Chat Adapter and n8n AI Assistant tools are here. They are for trusted local apps and testing.",
          done: "manual",
        },
        {
          id: "requirements",
          target: ".system-requirements",
          action: "read",
          title: "What your computer needs",
          say: "Relmio runs on Windows, macOS, Linux or WSL2 with Docker running.",
          done: "manual",
        },
      ],
    },
    {
      id: "configure",
      label: "Fill in the details",
      panel: "#configure-stage",
      badge: "Details ready",
      tips: [
        {
          id: "searxng-review",
          target: "#review-assistant-searxng-edit",
          action: "press",
          title: "Add search to existing tools",
          say: "This adds SearXNG search to Assistant tools Relmio already installed. Press Review SearXNG enablement to see the change first.",
          done: "clicked",
        },
        {
          id: "searxng-confirm",
          target: "#enable-assistant-searxng-confirm",
          action: "check",
          title: "Approve the search update",
          say: "Tick the box to start only the search service. n8n and the sandbox key stay as they are.",
          done: "checked",
        },
        {
          id: "searxng-enable",
          target: "#enable-assistant-searxng-button",
          action: "press",
          title: "Turn on search",
          say: "Press Enable SearXNG on owned Assistant tools, then copy any new setting it shows into n8n yourself.",
          done: "clicked",
        },
        ...siwcTips,
        {
          id: "oauth-sign-in",
          target: "#n8n-oauth-sign-in",
          action: "press",
          title: "Sign in to ChatGPT",
          say: "Press Sign in to ChatGPT to connect the account the sidecar will use.",
          done: "clicked",
        },
        {
          id: "port",
          target: "#local-port",
          action: "type",
          title: "Pick a local port",
          say: "A port is like a door number on this computer. Keep the number shown unless another app already uses it. The connection opens only on 127.0.0.1, so other computers cannot reach it.",
          example: "14502",
          done: "manual",
        },
        {
          id: "container",
          target: "#n8n-container",
          action: "choose",
          title: "Pick your n8n",
          say: "This list shows n8n containers running on this computer. Pick the one you use. Relmio does not change it.",
          find: "Only running n8n is listed. Start n8n first if it is missing, then press Refresh n8n discovery.",
          done: "manual",
        },
        {
          id: "network",
          target: "#n8n-network",
          action: "choose",
          title: "Pick the private network",
          say: "A Docker network is a private hallway that lets containers talk to each other. The helper joins this one so n8n can reach it.",
          done: "manual",
        },
        {
          id: "model",
          target: "#local-model-id",
          action: "choose",
          title: "Pick a model size",
          say: "Smaller models download faster and need less memory. With 8 GB of memory, start with Qwen3 1.7B or 0.6B. Review shows the memory and disk the model needs.",
          example: "qwen3:0.6b",
          find: "The docs suggest Qwen3.5 4B for 16 GB of memory and Qwen3.5 9B for 32 GB or more. Docker's own memory limit is what counts.",
          done: "manual",
        },
        {
          id: "assistant-warning",
          target: "#n8n-assistant-options",
          action: "read",
          title: "Testing only",
          say: "The Code Sandbox runner has root-level power on this computer. Use it for testing. For production, n8n recommends Daytona.",
          done: "manual",
        },
        {
          id: "assistant-search",
          target: "#include-local-searxng",
          action: "check",
          title: "Web search, optional",
          say: "Tick this only if n8n's Assistant needs private web search. It is off by default.",
          done: "manual",
        },
        {
          id: "ngrok-hostname",
          target: "#ngrok-hostname",
          action: "type",
          title: "Your ngrok address",
          say: "ngrok gives your new n8n a public web address. Type only the reserved hostname, with no https:// and no slash.",
          example: "workflow.example.ngrok.app",
          find: "In the ngrok dashboard, open Domains and create or pick a static domain.",
          done: "filled",
        },
        {
          id: "stack-port",
          target: "#n8n-stack-port",
          action: "type",
          title: "Local n8n port",
          say: "n8n opens on this computer at this port. Keep 5679 unless another app uses it.",
          example: "5679",
          done: "filled",
        },
        {
          id: "inspector-port",
          target: "#ngrok-inspector-port",
          action: "type",
          title: "ngrok inspector port",
          say: "ngrok's inspector page opens on this computer only. Keep 4041 unless another app uses it.",
          example: "4041",
          done: "filled",
        },
        {
          id: "timezone",
          target: "#n8n-stack-timezone",
          action: "type",
          title: "Your time zone",
          say: "Type the time zone for your new n8n, written the same way as the example.",
          example: "Asia/Manila",
          done: "filled",
        },
        {
          id: "assistant-mode",
          target: "#n8n-stack-assistant-mode",
          action: "choose",
          title: "Assistant tools, optional",
          say: "Disabled creates only n8n and ngrok. Code Sandbox adds the private sandbox for n8n's AI Assistant, and the last choice also adds web search.",
          done: "manual",
        },
        {
          id: "grok-reminder",
          target: "#supergrok-n8n-reminder",
          action: "read",
          title: "Two steps for Grok",
          say: "After install, run relmio grok login --n8n in a terminal to sign in to Grok. In n8n, turn Use Responses API off for this connection.",
          done: "manual",
        },
        {
          id: "detected",
          target: "#detected-local-integration-management",
          action: "read",
          title: "n8n already found",
          say: "Relmio found a running n8n. If you installed a Relmio companion before, open this to check it. For a new setup, keep going.",
          done: "manual",
        },
        {
          id: "guidance",
          target: "#target-guidance",
          action: "read",
          title: "How this connection signs in",
          say: "This box sums up how the connection signs in. A local key is separate and is not a Platform API key.",
          done: "manual",
        },
        {
          id: "review",
          target: "#review-button",
          action: "press",
          title: "Review the plan",
          say: "Press Review the plan. Nothing changes on this computer yet.",
          done: "clicked",
        },
        {
          id: "change",
          target: "#local-route-current",
          action: "read",
          title: "Wrong connection",
          say: "Press Change to go back and pick a different card.",
          done: "manual",
        },
      ],
    },
    {
      id: "review",
      label: "Review the plan",
      panel: "[data-step=\"2\"]",
      badge: "Plan approved",
      tips: [
        {
          id: "plan",
          target: "#review-endpoint",
          action: "read",
          title: "Check the plan",
          say: "This is everything Relmio will set up. Nothing has changed yet.",
          done: "manual",
        },
        {
          id: "budget",
          target: "#local-model-review-budget",
          action: "read",
          title: "Check memory and disk",
          say: "These numbers come from Docker on this computer. Confirm only if the model leaves room for n8n and your other apps.",
          done: "manual",
        },
        {
          id: "review-public-url",
          target: "#review-public-url",
          action: "read",
          title: "Your public link",
          say: "This is the public n8n address. Anyone can reach its sign-in prompt, so you will pick a strong password on the next screen.",
          done: "manual",
        },
        {
          id: "confirm",
          target: "#install-confirm",
          action: "check",
          title: "Approve the plan",
          say: "Tick this to let Relmio write its own files and start this container.",
          done: "checked",
        },
        {
          id: "migration",
          target: "#local-migration-consent",
          action: "check",
          title: "Replace the old service",
          say: "An older Relmio service is here. Tick this to stop only that one and keep its old sign-in offline. You will get a new key.",
          done: "checked",
        },
        {
          id: "replacement",
          target: "#local-replacement-consent",
          action: "check",
          title: "Use a fresh account",
          say: "The installed service is signed out. Tick this to replace it with the account you just signed in.",
          done: "checked",
        },
        {
          id: "to-install",
          target: "#install-settings-button",
          action: "press",
          title: "Continue to install",
          say: "Press Continue to install.",
          done: "clicked",
        },
      ],
    },
    {
      id: "install",
      label: "Install it",
      panel: "#install-panel",
      badge: "Installed",
      tips: [
        {
          id: "progress",
          target: "#install-progress",
          action: "wait",
          title: "Wait for the install",
          say: "Relmio is working. First Docker downloads can take several minutes, so keep this page open.",
          done: "hidden:#install-progress",
        },
        {
          id: "codex-warning",
          target: "#codex-install-warning",
          action: "read",
          title: "This key is powerful",
          say: "Anyone with this key can act through your ChatGPT sign-in. Treat it like your ChatGPT password and give it only to a trusted local app.",
          done: "manual",
        },
        {
          id: "sidecar-note",
          target: "#sidecar-install-note",
          action: "read",
          title: "You enter the key",
          say: "The sidecar is a small helper Relmio runs next to n8n. After install, you paste its one-time key into n8n yourself.",
          done: "manual",
        },
        {
          id: "assistant-note",
          target: "#assistant-install-note",
          action: "read",
          title: "Testing companion",
          say: "Relmio starts only the sandbox services and the search option you chose. Copy the settings it returns into n8n yourself.",
          done: "manual",
        },
        {
          id: "authtoken",
          target: "#ngrok-authtoken",
          action: "type",
          title: "Paste your ngrok token",
          say: "Paste one active agent token from ngrok. Paste the token only, without the ngrok config add-authtoken command.",
          find: "In the ngrok dashboard, open Your Authtoken. Authtokens under Settings lists the same kind of token.",
          done: "filled",
        },
        {
          id: "basic-user",
          target: "#ngrok-basic-auth-username",
          action: "type",
          title: "Make up a username",
          say: "Create a username for people who open your public n8n link. Use letters, numbers, hyphens or underscores. It does not come from ngrok, n8n or ChatGPT.",
          example: "workflow-admin",
          done: "filled",
        },
        {
          id: "basic-password",
          target: "#ngrok-basic-auth-password",
          action: "type",
          title: "Create a strong password",
          say: "Press Generate strong password, or type your own with at least 12 characters. Save it somewhere safe, because Relmio will not show it again.",
          done: "filled",
        },
        {
          id: "background",
          target: "#local-background-consent",
          action: "check",
          title: "Allow background workflows",
          say: "n8n runs workflows on its own, even when you are away. Tick this to let those workflows use this account's ChatGPT plan.",
          done: "checked",
        },
        {
          id: "install",
          target: "#install-button",
          action: "press",
          title: "Install on this computer",
          say: "Press Install on this computer and keep this page open until it finishes.",
          done: "clicked",
        },
      ],
    },
    {
      id: "ready",
      label: "Copy your settings",
      panel: "[data-step=\"4\"]",
      badge: "Connection ready",
      tips: [
        {
          id: "tester-endpoint",
          target: "#chat-tester-endpoint",
          action: "type",
          title: "Adapter address",
          say: "Type the Chat Adapter address shown above. Only a 127.0.0.1 address works here.",
          example: "http://127.0.0.1:14501",
          done: "filled",
        },
        {
          id: "tester-credential",
          target: "#chat-tester-credential",
          action: "type",
          title: "Paste the client credential",
          say: "Paste the client credential from this screen. The box clears when you secure it.",
          done: "filled",
        },
        {
          id: "tester-secure",
          target: "#chat-tester-secure",
          action: "press",
          title: "Secure the test",
          say: "Press Secure credential for this test to start a short test session.",
          done: "clicked",
        },
        {
          id: "tester-message",
          target: "#chat-tester-input",
          action: "type",
          title: "Send a test message",
          say: "Pick a model, type a short message and press Send test message. A real answer shows the connection works.",
          example: "Reply with exactly: bridge works",
          done: "filled",
        },
        {
          id: "owner-inspect",
          target: "#local-siwc-inspect-confirm",
          action: "check",
          title: "Allow a one-time look",
          say: "The service is stopped, so Relmio needs a short read to see its account. It does not start or edit n8n. Tick the box, then press Inspect stopped account.",
          done: "checked",
        },
        {
          id: "owner-confirm",
          target: "#local-siwc-owner-confirm",
          action: "check",
          title: "Pause or sign out",
          say: "Pause stops this service until you press Use ChatGPT plan. Sign out stops it until you sign in again. Tick the box first, then press the action you want.",
          find: "To remove Relmio from ChatGPT as well, use Disconnect under Settings, Security and login, Login connections, if ChatGPT lists it.",
          done: "checked",
        },
        {
          id: "owner-background",
          target: "#local-siwc-background-confirm",
          action: "check",
          title: "Allow background use again",
          say: "Turning plan use back on needs your approval for n8n background workflows again. Tick the box, then press Use ChatGPT plan.",
          done: "checked",
        },
        {
          id: "n8n-settings",
          target: "#result-n8n-settings",
          action: "read",
          title: "Add these to n8n yourself",
          say: "Copy these values into n8n's settings the way you normally run n8n. Relmio never edits or restarts n8n.",
          done: "manual",
        },
        {
          id: "rotate",
          target: "#rotate-credential-button",
          action: "press",
          title: "Make a new key",
          say: "Rotate makes a new key and turns off the old one once the new one works. Copy the new key before you leave.",
          done: "clicked",
        },
        {
          id: "remove-bridge",
          target: "#remove-bridge-confirm",
          action: "check",
          title: "Remove the bridge",
          say: "Tick this and press Remove bridge to delete only Relmio's sidecar and its private files. n8n stays.",
          done: "checked",
        },
        {
          id: "remove-supergrok",
          target: "#remove-supergrok-confirm",
          action: "check",
          title: "Remove Grok for n8n",
          say: "Tick this and press the remove button to delete only the Grok sidecar and its private files. n8n stays.",
          done: "checked",
        },
        {
          id: "remove-assistant",
          target: "#remove-assistant-confirm",
          action: "check",
          title: "Remove Assistant tools",
          say: "Tick this and press Remove Assistant tools to delete only the sandbox, search and their private files. n8n stays.",
          done: "checked",
        },
        {
          id: "resume-stack",
          target: "#resume-n8n-stack-button",
          action: "press",
          title: "Start your n8n again",
          say: "Your Relmio n8n and ngrok are stopped. Press Resume owned stack to start them. Your workflows stay in place.",
          done: "clicked",
        },
        {
          id: "model-retry",
          target: "#local-model-review-retry",
          action: "press",
          title: "Retry the model",
          say: "The model is not ready yet. Press Review retry. Retry keeps the files already downloaded.",
          done: "clicked",
        },
        {
          id: "model-confirm",
          target: "#local-model-action-confirm",
          action: "check",
          title: "Approve the model action",
          say: "Read the action above, then tick the box and press Apply reviewed action. Deleting the cache needs its own second box.",
          done: "checked",
        },
        {
          id: "model-status",
          target: "#local-model-state",
          action: "wait",
          title: "Wait for the model",
          say: "The model downloads and then answers a short test. Press Refresh model status to check. It is ready only after that test passes.",
          done: "visible:#local-model-settings",
        },
        {
          id: "model-settings",
          target: "#local-model-url",
          action: "read",
          title: "Fill in n8n",
          say: "In n8n, use this Base URL, the model ID and local-only as the API key. Turn Use Responses API off.",
          example: "http://n8n-local-model:11434/v1",
          done: "manual",
        },
        {
          id: "credential",
          target: "[data-copy-target=result-credential]",
          action: "press",
          title: "Copy your key now",
          say: "An API key is a password one app uses to talk to another. Relmio shows this one only now, so copy it into your app or n8n credential. It is not an OpenAI API key.",
          done: "clicked",
        },
        {
          id: "endpoint",
          target: "[data-copy-target=result-endpoint]",
          action: "press",
          title: "Copy the address",
          say: "Copy this address into your app or n8n credential as the Base URL.",
          done: "clicked",
        },
        {
          id: "sandbox-key",
          target: "[data-copy-target=result-sandbox-key]",
          action: "press",
          title: "Copy the sandbox key",
          say: "Relmio shows this sandbox key only once. Copy it into n8n's AI Assistant settings.",
          done: "clicked",
        },
        {
          id: "public-url",
          target: "[data-copy-target=result-public-url]",
          action: "press",
          title: "Test your public link",
          say: "Copy this link and open it in a private browser window. It must ask for your Basic Auth username and password before n8n loads.",
          done: "clicked",
        },
        {
          id: "model-pick",
          target: "#installed-siwc-model",
          action: "choose",
          title: "Pick a model",
          say: "Pick a model from this account's list for n8n. A listed model can still fail or reach a usage limit.",
          done: "manual",
        },
        {
          id: "remove-stack",
          target: "#remove-n8n-stack-confirm",
          action: "check",
          title: "Remove the new n8n",
          say: "Removing deletes this n8n's workflows and credentials for good. Export what you need first, then tick this and press Remove owned stack.",
          done: "manual",
        },
        {
          id: "usage-open",
          target: "#installed-usage-title",
          action: "press",
          title: "See your plan and usage",
          say: "Open Plan and usage to see the requests and tokens n8n sent through Relmio. These are not your plan's limits, which ChatGPT shows under Manage usage.",
          done: "visible:#installed-usage-status",
        },
        {
          id: "another",
          target: "#setup-another-local",
          action: "press",
          title: "Set up something else",
          say: "Press Choose another connection to add more. Copy any key first, because it is not shown again.",
          done: "manual",
        },
      ],
    },
  ],
  finish: {
    title: "Setup complete",
    say: "Your connection is running on this computer. Relmio does not show one-time keys again, so keep the copies you made.",
    next: [
      "Paste the address and key into your app or n8n",
      "Run a short test message",
      "Use Back to dashboard to see every connection",
    ],
  },
};
