/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/relmio-theme.ts
 * Command: astryx theme build app/relmio-theme.ts
 * Generated: 2026-08-02T01:16:28.648Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
