/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/relmio-theme.ts
 * Command: astryx theme build app/relmio-theme.ts
 * Generated: 2026-08-01T15:31:43.356Z
 */

/// <reference path="./relmio.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const relmioTheme: DefinedTheme;
