/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/relmio-theme.ts
 * Command: astryx theme build app/relmio-theme.ts
 * Generated: 2026-08-30T00:13:42.362Z
 */

/// <reference path="./relmio.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const relmioTheme: DefinedTheme;
